Algoritmo "contador"
// Disciplina   : Algoritmos
// Professor   : Agnaldo Carneiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Giovanna Karolina Neres da Costa(a)
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <-1
enquanto (contador <=5) faca
escreval (contador)
contador<-contador+1
fimenquanto

Fimalgoritmo