Algoritmo "Conversão de Moedas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Giovanna Karolina Neres da Costa
// Data atual  : 16/03/2026
Var
// Seção de Declarações das variáveis 
reais:real
dolares:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor que possuí em reais(R$)")
leia(reais)
dolares<-reais/5
escreval("Com R$", reais:5:2, " você pode comprar US$", dolares:5:2)

Fimalgoritmo