Algoritmo "Multiplos_3"
// Disciplina   : Algoritmos
// Professor   : Agnaldo Carneiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/04/2026
Var
// Seção de Declarações das variáveis 
i:inteiro
soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 até 10 faça
escreval("Os multiplos de 3 são:", (i * 3))
fimpara

Fimalgoritmo