Algoritmo "Numeroelevado"
// Disciplina   : Algoritmos
// Professor   : Agnaldo Carneiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Giovanna Karolina Neres da Costa
// Data atual  : 22/04/2026
Var
// Seção de Declarações das variáveis 
n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para n de 2 até 2 faça
escreval("2 ao quadrado é:",(n * n))
fimpara

Fimalgoritmo